### ISSUE TITLE
Canton Design System repo is private

### ISSUE THREAD

**Issue by aemxn** [31Carlton7/flutter_notes_app#5]
Hey, I'd like to learn building an app using Flutter by using this project as a learning ground. However, I can't pub get the pubspec.yaml because `canton_design_system` repo is private. I'm just assuming this UI lib is yours. Is there a reason why do you put it in private? Thanks.

**Comment by 31Carlton7** [comment]
A few people have complained about this repo being created with a separate UI Library, so I'm planning on restructuring it without a separate UI Library and including everything in one repo/app. In the meantime, I am working on a Budget/Savings app that also does not use a separate library, and will be releasing it soon. It will be fairly simple to learn from their too.
